spring:
  application:
    name: my_good_idea_api
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:h2:~/idea
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    generate-ddl: true
    hibernate:
      ddl-auto: update

